#
# These requirements were autogenerated by pipenv
# To regenerate from the project's Pipfile, run:
#
#    pipenv lock --requirements
#

-i https://pypi.org/simple
cachetools==5.3.1; python_version >= '3.7'
certifi==2023.7.22; python_version >= '3.6'
charset-normalizer==3.2.0; python_version >= '3.7'
db-dtypes==1.1.1; python_version >= '3.7'
google-api-core[grpc]==2.11.1; python_version >= '3.7'
google-auth-oauthlib==1.0.0; python_version >= '3.6'
google-auth==2.22.0; python_version >= '3.6'
google-cloud-bigquery-storage==2.22.0; python_version >= '3.7'
google-cloud-bigquery==3.11.4
google-cloud-core==2.3.3; python_version >= '3.7'
google-cloud-storage==2.10.0
google-crc32c==1.5.0; python_version >= '3.7'
google-resumable-media==2.5.0; python_version >= '3.7'
googleapis-common-protos==1.60.0; python_version >= '3.7'
grpcio-status==1.57.0
grpcio==1.57.0
idna==3.4; python_version >= '3.5'
numpy==1.24.4; python_version < '3.10'
oauthlib==3.2.2; python_version >= '3.6'
packaging==23.1; python_version >= '3.7'
pandas-gbq==0.19.2
pandas==2.0.3
proto-plus==1.22.3; python_version >= '3.6'
protobuf==4.24.1; python_version >= '3.7'
pyarrow==12.0.1
pyasn1-modules==0.3.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4, 3.5'
pyasn1==0.5.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4, 3.5'
pydata-google-auth==1.8.2
python-dateutil==2.8.2; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'
python-dotenv==1.0.0
pytz==2023.3
requests-oauthlib==1.3.1; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'
requests==2.31.0
rsa==4.9; python_version >= '3.6' and python_version < '4'
six==1.16.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'
sodapy==2.2.0
tzdata==2023.3; python_version >= '2'
urllib3==1.26.16; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4, 3.5'
